version: '2'

volumes:
    logs:
        driver: local

services:
    web:
        image: nginx:1.13.10-alpine
        ports:
          - "8080:80"
        links:
          - app
        volumes:
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - logs:/var/www/logs
            - .:/var/www/html

    app:
        build: ./docker/php
        env_file: .env
        environment:
            docker: "true"
        volumes:
            - .:/var/www/html
        links:
            - db

    db:
        image: mysql:5
        env_file: .env
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql_data:/var/lib/mysql