version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        build: ./docker/php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - db
            - db_test
    db:
        image: mysql:5
        env_file: .env
        ports:
            - 3306:3306
        volumes:
            - ./db/mysql_data:/var/lib/mysql
    db_test:
        image: mysql:5
        env_file: tests/.env
        ports:
            - 3307:3306
        volumes:
            - ./db/mysql_test_data:/var/lib/mysql