version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-fpm-node
      - image: circleci/mysql:5.7
      - image: selenium/standalone-chrome:3.7
        environment:
          HUB_PORT_4444_TCP_ADDR: 127.0.0.1
          HUB_PORT_4444_TCP_PORT: 4444

    working_directory: ~/slimbbs2

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Toyko"

    steps:
      - checkout

      - run: sudo apt install -y zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-enable pdo_mysql
      - run: sudo apt install -y libmemcached-dev
      - run: sudo docker-php-source extract
      - run: sudo git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached/
      - run: sudo docker-php-ext-install memcached
      - run: sudo composer self-update
      - run: sudo npm install -g npm@latest

      - run: echo 127.0.0.1 localhost | sudo tee -a /etc/hosts

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm run flow

      - run:
          command: php -S 127.0.0.1:8080 -t public public/index.php
          background: true

      - run: ./vendor/bin/phpmig migrate
      - run: ./vendor/bin/phpunit